package com.banfieldpatin.backend.compartido.auditoria;

public enum AccionAuditoria {
	LOGIN_EXITOSO,
	LOGIN_FALLIDO,
	LOGOUT,
	ADMIN_BOOTSTRAP,
	REGISTRO_POR_INVITACION,
	REGISTRO_FALLIDO,
	INVITACION_CREADA,
	INVITACION_REVOCADA,
	FAMILIA_CREADA,
	MFA_ENROLADO,
	MFA_CONFIRMADO,
	MFA_VERIFICADO,
	MFA_FALLO,
	MFA_REINICIADO
}
